import React from "react";

function Guidelines() {
  return (
    <div>
      <h1 className="guidelines-heading">Procedural Guidelines</h1>
      <p className="guidelines-p">Dear user / author, </p>
      <p className="guidelines-p">
        Welcome to Delcon. In order to submit a paper through this website, you
        would need to follow a simple 3-step procedure listed below.
      </p>
      <p className="guidelines-p">
        <span className="guidelines-red">Step 1</span>
        {""}
        <span className="guidelines-black">: Get Membership</span> - Getting
        membership to our site is the first step. You need to sign up using the
        Get Membership link. This allots you a unique{" "}
        <span className="guidelines-black">Member ID</span> which helps the
        website to recognize you. And it is{" "}
        <span className="guidelines-black">Free!</span> Please skip this step if
        you are already a member.
      </p>
      <p className="guidelines-p">
        Your e-mail account, provided by you in the membership form is
        considered as{" "}
        <span className="guidelines-black">registered e-mail ID</span> by us,
        and the same would be used by us for further communication with you. To
        begin with, your <span className="guidelines-black">Member ID</span> and
        <span className="guidelines-black">Password</span> would be mailed to
        you. Please mail us, using your registered mail ID, at
        <a href="conference@bvicam.ac.in">conference@bvicam.ac.in</a> in case
        you don't receive this e-mail.
      </p>
      <p className="guidelines-p">
        <span className="guidelines-black">
          Kindly Note that you do not need to re-register in case you had
          registered online as a member for any of the prior events like Delcon,
          NSC, BIJIT etc.
        </span>
      </p>
      <p className="guidelines-p">
        <span className="guidelines-red">Step 2</span>
        {""}
        <span className="guidelines-black">: Log in</span> - In order to submit
        a paper you need to log in to the web account using your{" "}
        <span className="guidelines-black">Member ID</span> and{" "}
        <span className="guidelines-black">Password</span>. You can do this by
        clicking here.
      </p>
      <p className="guidelines-p">
        <span className="guidelines-red">Step 3</span>
        <span className="guidelines-black">: Submit the paper</span> - You can
        now submit your paper using the Submit Paper link. Please note that all
        your co-authors must be members of this website and while submitting the
        paper you would need to provide their member IDs. When you submit a
        paper, a <span className="guidelines-black">Unique Paper ID</span> is
        allotted to it. Please use this ID for any queries regarding the paper,
        in future.
      </p>
      <p className="guidelines-p">
        <span className="guidelines-black">
          We also wish to inform you that plagiarised papers will not be
          accepted for Delcon-2024. The Delcon team will be checking plagiarism
          level of all the submitted papers for ensuring the originality of
          content using Turnitin. Hence, you are advised in your own interest,
          to use a tool like Turnitin, iThenticate, Viper, PlagScan etc. to
          check the plagiarism level of your manuscripts before submission. The
          originality report generated by the tool, may also be submitted at the
          time of paper submission.
        </span>
      </p>
      <p className="guidelines-p">
        Kindly note that we would carry out direct correspondence with only one
        author per paper (we name it as{" "}
        <span className="guidelines-black">Corresponding Author</span>). Thus,
        if your paper is co-authored by multiple members, all our e-mails would
        be sent to the e-mail account of the author nominated by you, as{" "}
        <span className="guidelines-black">Corresponding Author</span>. While
        submitting the paper, you can designate one of your co-authors to be
        responsible for correspondence by selecting his / her ID as the{" "}
        <span className="guidelines-black">Correspondence ID</span>. To begin
        with, a confirmation email along with the paper ID would be sent to him
        / her. Please mail us using your registered e-mail ID, at
        <a href="conference@bvicam.ac.in">conference@bvicam.ac.in</a> in case
        you don't receive this e-mail.
      </p>
      <p className="guidelines-p">
        You can always refer to our FAQs page which might be able to answer any
        further queries or contact us using the correspondence details available
        here.
      </p>
    </div>
  );
}

export default Guidelines;