import React from "react";

function Review() {
  return (
    <div>
      <h1 className="review-heading">
        Review Process, Publication and Indexing
      </h1>
      <p className="review_p">
        <span className="review_red">Plagiarism Policy:</span>{" "}
        <span className="review_black">
          Please note that plagiarised papers will not be accepted for
          Delcon-2024. The Delcon team will be checking plagiarism level of all
          the submitted papers for ensuring the originality of content using
          Turnitin. Hence, authors are advised in their own interest, to use a
          tool like Turnitin, iThenticate, Viper, PlagScan etc. to check the
          plagiarism level of their manuscripts before submission. The
          originality report generated by the tool, may also be submitted at the
          time of paper submission.
        </span>{" "}
      </p>
      <p className="review_p">
        The conference aims at carrying out two rounds of review process. In the
        first round, the papers submitted by the authors will be assessed on the
        basis of their technical suitability, scope of work and plagiarism. The
        corresponding authors of qualifying submissions will be intimated for
        their papers to be double blind reviewed by three experts on the basis
        of originality, novelty, clarity, completeness, relevance, significance
        and research contribution. Final decision regarding acceptance of papers
        will be based upon the review remarks received after the second round of
        the review process.
      </p>
      <p className="review_p">
        The shortlisted papers of all the tracks will be accepted for
        presentation and publication in the Soft Copy of Pre-Conference
        proceedings, bearing{" "}
        <span className="review_black">ISBN serial 978-93-80544-52-6</span>, to
        be published on the Delcon Website. Upon acceptance, authors will be
        required to
        <span className="review_black">register</span> and{" "}
        <span className="review_black">present</span> their papers.
      </p>
      <p className="review_p">
        Please note that{" "}
        <span className="review_red">
          papers will be published in the Pre-conference proceedings only if at
          least one of the authors is officially registered in advance (as
          specified in
        </span>{" "}
        <span className="review_blue">important dates</span>){" "}
        <span className="review_red">
          and he/she undertakes to present the paper.
        </span>
      </p>
      <p className="review_p">
        A chosen set of accepted and presented papers, as recommended by the
        Editorial Board, will also be published in the Hard Copy of the
        Conference Proceedings bearing{" "}
        <span className="review_black">ISBN serial 978-93-80544-53-3 .</span>
      </p>
      <p className="review_p">
        Accepted papers, after presentation, will be submitted for inclusion
        into IEEE Xplore subject to meeting IEEE Xplore’s scope and quality
        requirements.
      </p>
      <p className="review_p">
        <span className="review_black">Papers accepted for</span>{" "}
        <span className="review_red">Poster Presentation</span>{" "}
        <span className="review_black">
          are not eligible for publication, in either the soft or the hard copy
          of the proceedings.
        </span>
      </p>
    </div>
  );
}

export default Review;